apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-planner.fullname" . }}-secret
type: Opaque
stringData:
  USER_MAIL: {{ .Values.email.username }}
  USER_PASSWORD: {{ .Values.email.password }}
