{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-tbd-ingress
  labels:
    {{- include "event-planner.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /team-6/swagger-ui(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "event-planner.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}

          - path: /team-6/metrics
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "event-planner.fullname" $ }}
                port:
                  number: {{ $.Values.service.metricsPort }}

          - path: /team-6/(?!swagger-ui)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "event-planner.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.service.frontendPort }}

{{- end }}
