apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "event-planner.fullname" . }}-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
