apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-planner.fullname" . }}-postgresql
  labels:
    app: {{ include "event-planner.name" . }}
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ include "event-planner.name" . }}
    component: postgresql
