apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-planner.fullname" . }}-db-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.database }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
