apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-planner.fullname" . }}
  labels:
    {{- include "event-planner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: 8081
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "event-planner.selectorLabels" . | nindent 4 }}
