spring:
  application:
    name: event-planner

  datasource:
    url: "jdbc:postgresql://event-planner-postgresql:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /team-6/swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /team-6
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: /metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
