apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-infra.fullname" . }}-grafana
  labels:
    app: {{ include "k8s-infra.name" . }}
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "k8s-infra.name" . }}
      component: grafana
  template:
    metadata:
      labels:
        app: {{ include "k8s-infra.name" . }}
        component: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image }}"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/team-6/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          resources:
            limits:
              cpu: 0.3
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-infra.fullname" . }}-grafana
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    component: grafana

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-infra-ingress
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /team-6/grafana(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "k8s-infra.fullname" $ }}-grafana
                port:
                  number: 3000
