apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-infra.fullname" . }}-prometheus
  labels:
    app: {{ include "k8s-infra.name" . }}
    component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "k8s-infra.name" . }}
      component: prometheus
  template:
    metadata:
      labels:
        app: {{ include "k8s-infra.name" . }}
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image }}"
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 0.4
              memory: 400Mi
            requests:
              cpu: 0.4
              memory: 400Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-infra.fullname" . }}-prometheus
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-infra.selectorLabels" . | nindent 4 }}

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-tbd-ingress
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: /team-6/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "k8s-infra.fullname" . }}-prometheus
                port:
                  number: 9090

